controller_joint_names: ['', 'joint3', 'joint5', 'joint1', 'joint6', 'joint7', 'joint8', 'joint10', 'jjoint9', 'joint11', 'joint14', 'joint15', 'joint16', 'joint18', 'joint20', 'joint17', 'joint19', ]
